# kNN in python3

In [8]:
pwd

'C:\\pydev\\MLiA_py3'

In [9]:
import kNN

In [10]:
d = {'a':10, 'b':'hello', 'd':20}; d

{'a': 10, 'b': 'hello', 'd': 20}

In [11]:
d.get('a')

10

- sorted 함수에 대해서 봄!! 
    - option, key 값에 함수를 줄 수 있다. / lambda 함수도 쓰고!! 

In [12]:
import numpy as np

In [26]:
group, labels = kNN.createDataSet()

In [15]:
data_set = group

In [16]:
data_set_size = data_set.shape[0]; data_set_size

4

In [17]:
kNN.classify0([1, 0.8], group, labels, 3)

'A'

## python3 에서는 reload 방식이 python2와 다른다

In [6]:
import kNN

In [20]:
import importlib
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA_py3\\kNN.py'>

In [21]:
%timeit kNN.file2matrix('datingTestSet.txt')

100 loops, best of 3: 4.78 ms per loop


In [22]:
%timeit kNN.file2matrix_drop('datingTestSet.txt')

100 loops, best of 3: 15.2 ms per loop


- 파일 2번 읽어 들여서 하는 것이 훨씬 빨랐다!! 

# listing 2.2

In [28]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA_py3\\kNN.py'>

In [29]:
filename = 'datingTestSet.txt'

In [31]:
datingDateMat, datingLabels = kNN.file2matrix(filename)

In [32]:
normMat, ranges, minVals = kNN.autoNorm(datingDateMat)

In [33]:
print(normMat)
print(ranges)
print(minVals)

[[ 0.44832535  0.39805139  0.56233353]
 [ 0.15873259  0.34195467  0.98724416]
 [ 0.28542943  0.06892523  0.47449629]
 ..., 
 [ 0.29115949  0.50910294  0.51079493]
 [ 0.52711097  0.43665451  0.4290048 ]
 [ 0.47940793  0.3768091   0.78571804]]
[  9.12730000e+04   2.09193490e+01   1.69436100e+00]
[ 0.        0.        0.001156]


# 2.2.4 검사 : 분류기 검사

In [56]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA_py3\\kNN.py'>

In [57]:
kNN.datingClassTest(file='datingTestSet2.txt', k=7)

the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answe

# 2.2.5 사용, 값을 직접 받아서 !!!

In [73]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA_py3\\kNN.py'>

In [74]:
kNN.classifyPerson()

percentage of time spent playing video games?1
frequent flier miles earned per year?1
liters of ice cream consumed per year?1
You will probably like this person:  in small doses
